apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-driver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-driver
  template:
    metadata:
      labels:
        app: spark-driver
    spec:
      serviceAccountName: spark-driver
      containers:
      - name: spark-driver
        image: xavier418/spark-driver:3.5.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-cluster-admin-binding
subjects:
- kind: ServiceAccount
  name: spark-driver
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-driver
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: spark-driver-jupyter
spec:
  type: NodePort
  selector:
    app: spark-driver
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30088
---
apiVersion: v1
kind: Service
metadata:
  name: spark-driver-headless
spec:
  clusterIP: None
  selector:
    app: spark-driver
  ports:
    - port: 8888
      targetPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: spark-ui
spec:
  type: NodePort
  selector:
    app: spark-driver
  ports:
    - protocol: TCP
      port: 4040
      targetPort: 4040
      nodePort: 30089
